# Maven build container 

FROM maven:3.8.5-openjdk-11 AS maven_build

COPY pom.xml /tmp/

COPY src /tmp/src/

WORKDIR /tmp/

RUN mvn package

#pull base image

FROM eclipse-temurin:11

#maintainer 
MAINTAINER utpal.us12@gmail.com
#expose port 8080
EXPOSE 8080

#default command
CMD java -jar roche-fizz-buzz.jar

#copy hello world to docker image from builder image

COPY --from=maven_build /tmp/target/roche-fizz-buzz.jar roche-fizz-buzz.jar